name: Update README with Latest Block Height

on:
  schedule:
    - cron: '0 * * * *' # Запускается каждый час

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Fetch latest block height
      id: fetch_block_height
      run: |
        response=$(curl -s 'https://osmosis-rpc.polkachu.com/status?')
        echo "::set-output name=block_height::$(echo $response | jq -r '.result.sync_info.latest_block_height')"
        
    - name: Update README.md
      run: |
        block_height="${{ steps.fetch_block_height.outputs.block_height }}"
        sed -i "s/Latest Block Height: [0-9]*/Latest Block Height: $block_height/" README.md
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest block height" || exit 0
        git push
